config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  get 'articles', to: 'articles#index', as: :articles

  get 'articles/:id', to: 'articles#show', as: :article

  get 'articles/new', to: 'articles#new', as: :new

  post 'articles', to: 'articles#create', as: :create

  get 'articles/:id/edit', to: 'articles#edit', as: :edit

  patch 'articles/:id', to: 'articles#update', as: :update

  delete 'articles/:id', to: 'articles#destroy', as: :destroy

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    find
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
  end

  def edit
    find
  end

  def update
    find
    @article.update(article_params)
  end

  def destroy
    find
    @article.destroy
    redirect_to root_path
  end

  private

  def find
    @article = Article.find(params[:id])
  end

  def task_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<div class="major_index_container">
  <div class="title">
    <h1>These are Hipster articles</h1>
  </div>
  <div class="container">
    <%= @articles.each do |a| %>
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="card">
        <h2><%= link_to a.title, article_path(a) %></h2>
        <p><%= a.content %></p>
        <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>